#define MICROPY_HW_BOARD_NAME           "ATK-DNESP32S3"
#define MICROPY_HW_MCU_NAME             "ESP32-S3R8"

#define MICROPY_HW_ENABLE_UART_REPL     (1)

#define MICROPY_HW_ENABLE_USBDEV        (0)
#define MICROPY_HW_USB_CDC              (0)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG  (0)

#define MICROPY_HW_ESP32S3_EXTENDED_IO  (1)
